### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by Pradeepkumarbk**
This will add the unit test cases for:
- main,go
- iops.go
- latency.go
- throughput.go

Signed-off-by: Pradeepkumarbk <pradeepkumar.bk96@gmail.com>

### CODE REVIEW

**Comment by Akash4927** [comment]
@Pradeepkumarbk Can you share the output of `go test ./... -cover`

**Comment by Pradeepkumarbk** [comment]
@Akash4927 
```
PASS
coverage: 31.4% of statements
ok  	github.com/weaveworks-plugins/scope-plugin	0.107s
```

**Comment by satyamz** [comment]
@Pradeepkumarbk 
Why this 
> PASS
> coverage: 31.4% of statements
> ok  	github.com/weaveworks-plugins/scope-plugin	0.107s


`weaveworks-plugins ` ?

**Comment by Pradeepkumarbk** [comment]
@satyamz Thats my directory, I had cloned our repo there.
```
PASS
coverage: 31.4% of statements
ok  	github.com/openebs-plugin/scope-plugin	0.051s
```
changed.

**Pull request merged**
